import { useEffect, useMemo, useState } from 'react'
import { DEMO_NOW, asMillis, systemNowIso } from '../../lib/demoClock'
import { hideFixtureEpisode, removeUserEpisode, resetPatientEpisodes, restoreFixtureEpisode, saveFixtureOverride, saveUserEpisode, userEpisodesFor } from '../../lib/localStore'
import EpisodeForm from './EpisodeForm'
import { formatDuration } from './duration'

const formatDateTime = (iso) => new Intl.DateTimeFormat('en', { weekday: 'short', month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit', timeZone: 'Asia/Shanghai' }).format(new Date(iso))

export default function DiaryPage({ patient, episodes, onChanged }) {
  const [formMode, setFormMode] = useState(null), [editingId, setEditingId] = useState(null), [notice, setNotice] = useState(''), [deleting, setDeleting] = useState(null), [undo, setUndo] = useState(null), [filter, setFilter] = useState('all')
  const { persistent } = userEpisodesFor(patient.id)
  const editing = editingId ? episodes.find((episode) => episode.id === editingId) ?? null : null
  useEffect(() => { setFormMode(null); setEditingId(null); setDeleting(null); setUndo(null); setNotice('') }, [patient.id])
  useEffect(() => { if (!undo) return undefined; const timer = setTimeout(() => setUndo(null), 30000); return () => clearTimeout(timer) }, [undo])
  const save = (episode) => { const result = episode.origin === 'fixture' ? saveFixtureOverride(episode) : saveUserEpisode(episode); if (!result?.persistent) { setNotice(result?.error || 'Could not save this entry on this device.'); return } onChanged(); setFormMode(null); setEditingId(null); setNotice('Entry saved') }
  const deleteEntry = () => { if (deleting.origin === 'fixture') hideFixtureEpisode(patient.id, deleting.id); else removeUserEpisode(patient.id, deleting.id); setUndo(deleting); setDeleting(null); onChanged(); setNotice('Entry deleted. Undo available for 30 seconds.') }
  const visible = useMemo(() => episodes.filter((episode) => filter === 'all' || filter === 'ongoing' && episode.endAt === null && !episode.endUnknown || filter === 'mine' && episode.origin === 'user' || filter === 'last30' && asMillis(DEMO_NOW) - asMillis(episode.startAt) <= 30 * 86400000), [episodes, filter])
  return <section><header className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-sm font-semibold text-indigo-600">Synthetic historical reference: 20 Mar 2025</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-900">Migraine Diary</h1><p className="mt-2 text-slate-600">Fixture records are read-only. Your entries and hidden-demo choices are stored only in this browser for {patient.name}.</p></div><div className="flex flex-wrap gap-2"><button onClick={() => { setEditingId(null); setFormMode('now') }} className="min-h-11 rounded-xl bg-indigo-600 px-4 text-sm font-semibold text-white">Happening now</button><button onClick={() => { setEditingId(null); setFormMode('past') }} className="min-h-11 rounded-xl bg-indigo-50 px-4 text-sm font-semibold text-indigo-700">Log a past attack</button></div></header>
    {!persistent && <p className="mt-5 rounded-xl bg-amber-50 p-3 text-sm text-amber-800">Entries will not be saved on this device.</p>}<p aria-live="polite" className="mt-3 text-sm font-medium text-indigo-700">{notice}</p>
    {(formMode || editing) && <div className="mt-6"><EpisodeForm key={editing?.id ?? formMode} patientId={patient.id} episode={editing} happeningNow={formMode === 'now'} onSave={save} onCancel={() => { setFormMode(null); setEditingId(null) }} /></div>}
    <section className="mt-7 rounded-3xl border border-blue-100 bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-bold text-slate-900">Recorded entries</h2><p className="mt-1 text-sm text-slate-500">{episodes.filter((entry) => entry.origin === 'fixture').length} visible entries are demo data.</p></div><button onClick={() => { resetPatientEpisodes(patient.id); onChanged(); setNotice('Demo data restored for this patient.') }} className="min-h-11 rounded-xl bg-slate-100 px-4 text-sm font-semibold text-slate-700">Reset demo data</button></div><div className="mt-4 flex flex-wrap gap-2" role="group" aria-label="Filter diary entries">{[['all', 'All'], ['ongoing', 'Ongoing'], ['last30', 'Last 30 days'], ['mine', 'Logged by me']].map(([id, label]) => <button key={id} onClick={() => setFilter(id)} className={`rounded-full px-3 py-2 text-sm ${filter === id ? 'bg-indigo-600 text-white' : 'bg-indigo-50 text-indigo-700'}`}>{label}</button>)}</div><div className="mt-5 space-y-3">{visible.length ? visible.map((episode) => <EpisodeRow key={episode.id} episode={episode} onEdit={() => { setEditingId(episode.id); setFormMode(null) }} onDelete={() => setDeleting(episode)} onMarkEnded={() => { const now = systemNowIso(); saveUserEpisode({ ...episode, endAt: now, endUnknown: false, updatedAt: now }); onChanged(); setNotice('Entry updated') }} />) : <p className="rounded-2xl bg-slate-50 p-5 text-sm text-slate-600">No entries match this filter.</p>}</div></section>
    {deleting && <Dialog title="Delete this entry?" body={deleting.origin === 'fixture' ? 'This hides the synthetic demo entry on this device. Reset demo data restores it.' : 'This cannot be undone after 30 seconds.'} confirm="Delete entry" onConfirm={deleteEntry} onCancel={() => setDeleting(null)} />}{undo && <div className="fixed bottom-20 left-1/2 z-30 flex -translate-x-1/2 items-center gap-3 rounded-xl bg-slate-900 px-4 py-3 text-sm text-white">Entry deleted <button onClick={() => { if (undo.origin === 'fixture') restoreFixtureEpisode(patient.id, undo.id); else saveUserEpisode(undo); setUndo(null); onChanged(); setNotice('Entry restored') }} className="font-bold text-violet-200">Undo</button></div>}
  </section>
}
function EpisodeRow({ episode, onEdit, onDelete, onMarkEnded }) { const ongoing = episode.endAt === null && !episode.endUnknown; return <article className={`rounded-2xl border bg-slate-50 p-4 ${ongoing ? 'border-l-4 border-l-amber-400' : 'border-slate-100'}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-bold text-slate-800">{formatDateTime(episode.startAt)}</p><p className="mt-1 text-sm text-slate-600">{ongoing ? <span role="status" className="font-semibold text-amber-700">Ongoing</span> : episode.endUnknown ? 'End time not logged' : `${formatDuration(episode.startAt, episode.endAt)} · ended ${formatDateTime(episode.endAt)}`}</p></div><div className="flex gap-2"><span className="rounded-full bg-white px-3 py-1 text-xs font-bold text-slate-700">{episode.peakSeverity === null ? 'Severity unknown' : `${episode.peakSeverity}/10 worst`}</span><span className="rounded-full bg-violet-100 px-3 py-1 text-xs font-bold text-violet-700">{episode.origin === 'fixture' ? 'Demo' : 'You'}</span></div></div><div className="mt-3 flex flex-wrap gap-2">{episode.associatedSymptoms.map((symptom) => <span key={symptom} className="rounded-full bg-white px-2 py-1 text-xs text-slate-600">{symptom.replaceAll('_', ' ')}</span>)}</div>{episode.notes && <p className="mt-2 text-sm text-slate-600">{episode.notes}</p>}<div className="mt-4 flex gap-2">{ongoing && episode.origin === 'user' && <button onClick={onMarkEnded} className="min-h-11 rounded-xl bg-amber-100 px-3 text-sm font-semibold text-amber-800">Mark as ended</button>}<button aria-label={episode.origin === 'fixture' ? 'Edit demo entry' : 'Edit entry'} onClick={onEdit} className="min-h-11 rounded-xl bg-indigo-50 px-3 text-sm font-semibold text-indigo-700">Edit</button><button aria-label={episode.origin === 'fixture' ? 'Delete demo entry' : 'Delete entry'} onClick={onDelete} className="min-h-11 rounded-xl bg-rose-50 px-3 text-sm font-semibold text-rose-700">Delete</button></div></article> }
function Dialog({ title, body, confirm, onConfirm, onCancel }) { return <div className="fixed inset-0 z-40 grid place-items-center bg-slate-900/30 p-5" role="dialog" aria-modal="true" aria-label={title}><div className="w-full max-w-sm rounded-3xl bg-white p-6 shadow-xl"><h2 className="text-lg font-bold text-slate-900">{title}</h2><p className="mt-2 text-sm text-slate-600">{body}</p><div className="mt-6 flex justify-end gap-3"><button onClick={onCancel} className="min-h-11 rounded-xl bg-slate-100 px-4 text-sm font-semibold">Cancel</button><button onClick={onConfirm} className="min-h-11 rounded-xl bg-indigo-600 px-4 text-sm font-semibold text-white">{confirm}</button></div></div></div> }
