export const CALENDAR_STORE_KEY = 'careloop.calendar.v1'
const EMPTY = () => ({ version: 1, byPatient: { usr_ava: { periodStarts: [], periodDays: [], hiddenPeriodDayIds: [] }, usr_mei: { periodStarts: [], periodDays: [], hiddenPeriodDayIds: [] }, usr_sofia: { periodStarts: [], periodDays: [], hiddenPeriodDayIds: [] } }, monthByPatient: {} })
const clone = (value) => JSON.parse(JSON.stringify(value))
const usable = (storage) => storage && typeof storage.getItem === 'function' && typeof storage.setItem === 'function'
export function readCalendarStore(storage = globalThis.localStorage) { if (!usable(storage)) return { store: EMPTY(), persistent: false }; try { const raw = storage.getItem(CALENDAR_STORE_KEY); if (!raw) return { store: EMPTY(), persistent: true }; const data = JSON.parse(raw); if (data?.version !== 1) throw new Error('bad calendar store'); return { store: { ...EMPTY(), ...data, byPatient: { ...EMPTY().byPatient, ...data.byPatient }, monthByPatient: data.monthByPatient ?? {} }, persistent: true } } catch { return { store: EMPTY(), persistent: false } } }
const write = (store, storage) => { if (!usable(storage)) return { persistent: false }; try { storage.setItem(CALENDAR_STORE_KEY, JSON.stringify(store)); return { persistent: true } } catch { return { persistent: false } } }
export const calendarDataFor = (patientId, storage) => { const { store, persistent } = readCalendarStore(storage); return { ...(store.byPatient[patientId] ?? { periodStarts: [], periodDays: [], hiddenPeriodDayIds: [] }), persistent } }
export function savePeriodStart(record, storage = globalThis.localStorage) { const { store } = readCalendarStore(storage); const data = store.byPatient[record.patientId] ?? { periodStarts: [], periodDays: [], hiddenPeriodDayIds: [] }; const index = data.periodStarts.findIndex((item) => item.id === record.id); data.periodStarts = index < 0 ? [...data.periodStarts, record] : data.periodStarts.map((item) => item.id === record.id ? record : item); store.byPatient[record.patientId] = data; return write(store, storage) }
export function savePeriodDay(record, storage = globalThis.localStorage) { const { store } = readCalendarStore(storage); const data = store.byPatient[record.patientId] ?? { periodStarts: [], periodDays: [], hiddenPeriodDayIds: [] }; const index = data.periodDays.findIndex((item) => item.id === record.id); data.periodDays = index < 0 ? [...data.periodDays, record] : data.periodDays.map((item) => item.id === record.id ? record : item); store.byPatient[record.patientId] = data; return write(store, storage) }
export function deletePeriodRecord(patientId, kind, id, storage = globalThis.localStorage) { const { store } = readCalendarStore(storage); const data = store.byPatient[patientId] ?? { periodStarts: [], periodDays: [], hiddenPeriodDayIds: [] }; data[kind] = data[kind].filter((item) => item.id !== id); store.byPatient[patientId] = data; return write(store, storage) }
export function resetCalendar(patientId, storage = globalThis.localStorage) { const { store } = readCalendarStore(storage); store.byPatient[patientId] = { periodStarts: [], periodDays: [], hiddenPeriodDayIds: [] }; return write(store, storage) }
export function calendarMonthFor(patientId, fallback, storage = globalThis.localStorage) { const { store } = readCalendarStore(storage); return store.monthByPatient[patientId] ?? fallback }
export function saveCalendarMonth(patientId, month, storage = globalThis.localStorage) { const { store } = readCalendarStore(storage); store.monthByPatient[patientId] = month; return write(store, storage) }
