import { useEffect, useState } from 'react'

const pages = [
  { id: 'dashboard', label: 'Dashboard', icon: '⌂' }, { id: 'calendar', label: 'Cycle Calendar', icon: '◷' },
  { id: 'diary', label: 'Migraine Diary', icon: '✦' }, { id: 'medication', label: 'Medication Tracker', icon: '⊹' },
  { id: 'insights', label: 'AI Insights', icon: '◌' }, { id: 'doctor', label: 'Doctor Preparation', icon: '▣' },
]
const pageDetails = {
  calendar: ['Cycle Calendar', 'See your cycle and migraine history in one calm view.'], diary: ['Migraine Diary', 'Record how you feel and the context around each migraine.'],
  medication: ['Medication Tracker', 'Keep an organized view of medications and reminders.'], insights: ['AI Insights', 'Patterns and prompts will appear here once connected.'],
  doctor: ['Doctor Preparation', 'Gather a clear visit summary and questions for your clinician.'],
}
const getPage = () => location.hash.replace('#/', '') || 'dashboard'

export default function App() {
  const [activePage, setActivePage] = useState(getPage)
  useEffect(() => { const update = () => setActivePage(getPage()); addEventListener('hashchange', update); return () => removeEventListener('hashchange', update) }, [])
  const navigate = (id) => { location.hash = `/${id}`; setActivePage(id) }
  return <div className="min-h-screen bg-[#f7f8ff] text-slate-800">
    <aside className="fixed inset-y-0 left-0 z-10 hidden w-68 flex-col border-r border-indigo-100 bg-white px-5 py-7 lg:flex"><Brand /><Navigation activePage={activePage} navigate={navigate} /><SidebarFooter /></aside>
    <header className="sticky top-0 z-10 flex items-center justify-between border-b border-indigo-100 bg-white/90 px-5 py-4 backdrop-blur lg:ml-68 lg:hidden"><Brand compact /><button className="rounded-xl bg-indigo-50 px-3 py-2 text-sm font-semibold text-indigo-700" onClick={() => navigate('dashboard')}>Dashboard</button></header>
    <main className="pb-24 lg:ml-68 lg:pb-10"><div className="mx-auto max-w-6xl px-5 py-7 sm:px-8 lg:px-10 lg:py-10">{activePage === 'dashboard' ? <Dashboard /> : <Placeholder page={pageDetails[activePage] || pageDetails.calendar} />}</div></main>
    <nav className="fixed inset-x-0 bottom-0 z-20 flex justify-around border-t border-indigo-100 bg-white px-1 py-2 lg:hidden">{pages.map((page) => <button key={page.id} onClick={() => navigate(page.id)} className={`flex min-w-0 flex-1 flex-col items-center gap-0.5 rounded-lg px-0.5 py-1 text-[9px] font-medium ${activePage === page.id ? 'text-indigo-700' : 'text-slate-500'}`}><span className="text-lg">{page.icon}</span>{page.label.split(' ')[0]}</button>)}</nav>
  </div>
}
function Brand({ compact = false }) { return <div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-2xl bg-gradient-to-br from-blue-600 to-violet-500 text-xl text-white shadow-sm">⌁</div>{!compact && <div><p className="text-lg font-bold tracking-tight text-slate-900">CareLoop</p><p className="text-xs text-slate-500">Your care, in rhythm</p></div>}</div> }
function Navigation({ activePage, navigate }) { return <nav className="mt-10 space-y-1">{pages.map((page) => <button key={page.id} onClick={() => navigate(page.id)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm font-semibold transition ${activePage === page.id ? 'bg-indigo-50 text-indigo-700' : 'text-slate-600 hover:bg-slate-50'}`}><span className="grid size-6 place-items-center text-base">{page.icon}</span>{page.label}</button>)}</nav> }
function SidebarFooter() { return <div className="mt-auto rounded-2xl bg-gradient-to-br from-blue-50 to-violet-50 p-4"><p className="text-xs font-bold uppercase tracking-wider text-indigo-600">Demo workspace</p><p className="mt-2 text-xs leading-5 text-slate-600">All patient details and health information shown are synthetic.</p></div> }
function Dashboard() { return <>
  <div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-sm font-semibold text-indigo-600">Friday, 9 October</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-900">Good morning, Maya</h1><p className="mt-2 max-w-xl text-slate-600">A gentle overview of what’s ahead in your care loop.</p></div><span className="w-fit rounded-full border border-violet-200 bg-violet-50 px-3 py-1.5 text-xs font-semibold text-violet-700">Synthetic demonstration data</span></div>
  <section className="mt-8 grid gap-5 md:grid-cols-3"><StatusCard label="Cycle day" value="18" detail="Estimated next period in 10 days" accent="blue" /><StatusCard label="Today’s check-in" value="Not logged" detail="A 30-second check-in can help." accent="violet" /><StatusCard label="Migraine-free days" value="12" detail="Over the last 30 days" accent="sky" /></section>
  <section className="mt-7 grid gap-6 lg:grid-cols-[1.45fr_1fr]"><div className="rounded-3xl bg-white p-6 shadow-[0_8px_30px_rgba(59,76,155,0.07)]"><div className="flex items-center justify-between"><div><h2 className="text-lg font-bold text-slate-900">Your next few days</h2><p className="mt-1 text-sm text-slate-500">Placeholder timeline • synthetic data</p></div><button className="text-sm font-semibold text-indigo-600">View calendar</button></div><div className="mt-7 grid grid-cols-5 gap-2"><Day day="9" label="Today" state="today" /><Day day="10" label="Sat" /><Day day="11" label="Sun" /><Day day="12" label="Mon" state="soft" /><Day day="13" label="Tue" state="soft" /></div><div className="mt-6 flex gap-5 text-xs text-slate-500"><span><i className="mr-1 inline-block size-2 rounded-full bg-indigo-500" />Today</span><span><i className="mr-1 inline-block size-2 rounded-full bg-violet-200" />Estimated window</span></div></div><div className="rounded-3xl bg-gradient-to-br from-[#eaf4ff] to-[#f3eeff] p-6"><p className="text-sm font-bold text-indigo-700">A small moment for you</p><h2 className="mt-2 text-xl font-bold text-slate-900">How are you feeling today?</h2><p className="mt-2 text-sm leading-6 text-slate-600">Check-in tools are coming soon. For now, this is a placeholder only.</p><button className="mt-5 rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white shadow-sm">Start check-in</button></div></section>
  <section className="mt-7 rounded-3xl border border-blue-100 bg-white p-6"><p className="text-sm font-bold text-slate-900">Getting started</p><p className="mt-1 text-sm text-slate-500">The rest of CareLoop is ready to explore. Features are intentionally placeholders for this first build.</p><div className="mt-5 grid gap-3 sm:grid-cols-3"><MiniStep number="1" title="Add a cycle" /><MiniStep number="2" title="Log a migraine" /><MiniStep number="3" title="Prepare for a visit" /></div></section>
  </> }
function StatusCard({ label, value, detail, accent }) { const styles = { blue: 'border-blue-100 bg-blue-50', violet: 'border-violet-100 bg-violet-50', sky: 'border-sky-100 bg-sky-50' }; return <article className={`rounded-3xl border p-5 ${styles[accent]}`}><p className="text-sm font-semibold text-slate-600">{label}</p><p className="mt-3 text-3xl font-bold tracking-tight text-slate-900">{value}</p><p className="mt-2 text-xs text-slate-500">{detail}</p></article> }
function Day({ day, label, state }) { return <div className={`rounded-2xl p-3 text-center ${state === 'today' ? 'bg-indigo-600 text-white' : state === 'soft' ? 'bg-violet-100 text-violet-800' : 'bg-slate-50 text-slate-700'}`}><p className="text-xs font-medium opacity-75">{label}</p><p className="mt-1 text-lg font-bold">{day}</p></div> }
function MiniStep({ number, title }) { return <div className="flex items-center gap-3 rounded-2xl bg-slate-50 p-4"><span className="grid size-7 place-items-center rounded-full bg-indigo-100 text-xs font-bold text-indigo-700">{number}</span><span className="text-sm font-semibold text-slate-700">{title}</span></div> }
function Placeholder({ page }) { return <section className="grid min-h-[65vh] place-items-center rounded-3xl border border-dashed border-indigo-200 bg-white p-8 text-center"><div><div className="mx-auto grid size-14 place-items-center rounded-2xl bg-indigo-50 text-2xl text-indigo-600">⌁</div><h1 className="mt-5 text-3xl font-bold tracking-tight text-slate-900">{page[0]}</h1><p className="mx-auto mt-3 max-w-md text-slate-600">{page[1]}</p><p className="mt-6 text-sm font-medium text-violet-700">Coming soon — placeholder page</p><p className="mt-2 text-xs text-slate-400">All future example data will be synthetic.</p></div></section> }
