import { useEffect, useState } from 'react'
import { DEMO_DATE, demoPatients } from './data/demoPatients'
import { selectDemoPatient } from './data/demoPatientModel'

const pages = [
  { id: 'dashboard', label: 'Dashboard', icon: '⌂' }, { id: 'calendar', label: 'Cycle Calendar', icon: '◷' },
  { id: 'diary', label: 'Migraine Diary', icon: '✦' }, { id: 'medication', label: 'Medication Tracker', icon: '⊹' },
  { id: 'insights', label: 'AI Insights', icon: '◌' }, { id: 'doctor', label: 'Doctor Preparation', icon: '▣' },
]
const pageDetails = {
  calendar: ['Cycle Calendar', 'See your cycle and migraine history in one calm view.'], diary: ['Migraine Diary', 'Record how you feel and the context around each migraine.'],
  medication: ['Medication Tracker', 'Keep an organized view of medications and reminders.'], insights: ['AI Insights', 'Patterns and prompts will appear here once connected.'],
  doctor: ['Doctor Preparation', 'Gather a clear visit summary and questions for your clinician.'],
}
const getPage = () => location.hash.replace('#/', '') || 'dashboard'

export default function App() {
  const [activePage, setActivePage] = useState(getPage)
  const [patientId, setPatientId] = useState(demoPatients[0].id)
  const patient = selectDemoPatient(demoPatients, patientId)
  useEffect(() => { const update = () => setActivePage(getPage()); addEventListener('hashchange', update); return () => removeEventListener('hashchange', update) }, [])
  const navigate = (id) => { location.hash = `/${id}`; setActivePage(id) }
  return <div className="min-h-screen bg-[#f7f8ff] text-slate-800">
    <aside className="fixed inset-y-0 left-0 z-10 hidden w-68 flex-col border-r border-indigo-100 bg-white px-5 py-7 lg:flex"><Brand /><Navigation activePage={activePage} navigate={navigate} /><SidebarFooter /></aside>
    <header className="sticky top-0 z-10 flex items-center justify-between border-b border-indigo-100 bg-white/90 px-5 py-4 backdrop-blur lg:ml-68 lg:hidden"><Brand compact /><button className="rounded-xl bg-indigo-50 px-3 py-2 text-sm font-semibold text-indigo-700" onClick={() => navigate('dashboard')}>Dashboard</button></header>
    <main className="pb-24 lg:ml-68 lg:pb-10"><div className="mx-auto max-w-6xl px-5 py-7 sm:px-8 lg:px-10 lg:py-10">{activePage === 'dashboard' ? <Dashboard patient={patient} onPatientChange={setPatientId} navigate={navigate} /> : <Placeholder page={pageDetails[activePage] || pageDetails.calendar} />}</div></main>
    <nav className="fixed inset-x-0 bottom-0 z-20 flex justify-around border-t border-indigo-100 bg-white px-1 py-2 lg:hidden">{pages.map((page) => <button key={page.id} onClick={() => navigate(page.id)} className={`flex min-w-0 flex-1 flex-col items-center gap-0.5 rounded-lg px-0.5 py-1 text-[9px] font-medium ${activePage === page.id ? 'text-indigo-700' : 'text-slate-500'}`}><span className="text-lg">{page.icon}</span>{page.label.split(' ')[0]}</button>)}</nav>
  </div>
}
function Brand({ compact = false }) { return <div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-2xl bg-gradient-to-br from-blue-600 to-violet-500 text-xl text-white shadow-sm">⌁</div>{!compact && <div><p className="text-lg font-bold tracking-tight text-slate-900">CareLoop</p><p className="text-xs text-slate-500">Your care, in rhythm</p></div>}</div> }
function Navigation({ activePage, navigate }) { return <nav className="mt-10 space-y-1">{pages.map((page) => <button key={page.id} onClick={() => navigate(page.id)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm font-semibold transition ${activePage === page.id ? 'bg-indigo-50 text-indigo-700' : 'text-slate-600 hover:bg-slate-50'}`}><span className="grid size-6 place-items-center text-base">{page.icon}</span>{page.label}</button>)}</nav> }
function SidebarFooter() { return <div className="mt-auto rounded-2xl bg-gradient-to-br from-blue-50 to-violet-50 p-4"><p className="text-xs font-bold uppercase tracking-wider text-indigo-600">Demo workspace</p><p className="mt-2 text-xs leading-5 text-slate-600">All patient details and health information shown are synthetic.</p></div> }
function Dashboard({ patient, onPatientChange, navigate }) { return <>
  <div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-sm font-semibold text-indigo-600">Demo date · {formatDate(DEMO_DATE)}</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-900">Welcome, {patient.name}</h1><p className="mt-2 max-w-xl text-slate-600">A historical snapshot from your CareLoop demo workspace.</p></div><span className="w-fit rounded-full border border-violet-200 bg-violet-50 px-3 py-1.5 text-xs font-semibold text-violet-700">Synthetic historical data</span></div>
  <section className="mt-6 rounded-3xl border border-blue-100 bg-white p-5 shadow-[0_8px_30px_rgba(59,76,155,0.05)]"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-bold text-slate-900">Demo patient</h2><p className="mt-1 text-sm text-slate-500">Switching changes only the locally bundled fictional history.</p></div><div className="flex flex-wrap gap-2" role="group" aria-label="Select demo patient">{demoPatients.map((candidate) => <button key={candidate.id} onClick={() => onPatientChange(candidate.id)} className={`rounded-xl px-4 py-2 text-sm font-semibold transition ${candidate.id === patient.id ? 'bg-indigo-600 text-white shadow-sm' : 'bg-indigo-50 text-indigo-700 hover:bg-indigo-100'}`}>{candidate.name}</button>)}</div></div></section>
  <section className="mt-7 grid gap-5 md:grid-cols-3"><StatusCard label="Recorded cycles" value={patient.cycles.length} detail={`${patient.dataSufficiency.completeCycles} completed`} accent="blue" /><StatusCard label="Recorded migraine episodes" value={patient.episodes.length} detail="From this synthetic history" accent="violet" /><StatusCard label="Data completeness" value={`Level ${patient.dataSufficiency.level}`} detail={`${patient.dataSufficiency.loggedDays} daily logs recorded`} accent="sky" /></section>
  <section className="mt-7 grid gap-6 lg:grid-cols-[1.35fr_1fr]"><div className="rounded-3xl bg-white p-6 shadow-[0_8px_30px_rgba(59,76,155,0.07)]"><div className="flex items-center justify-between"><div><h2 className="text-lg font-bold text-slate-900">Recorded cycle history</h2><p className="mt-1 text-sm text-slate-500">As recorded — no prediction or clinical interpretation.</p></div><button onClick={() => navigate('calendar')} className="text-sm font-semibold text-indigo-600">View calendar</button></div><div className="mt-5 space-y-3">{patient.cycles.map((cycle, index) => <div key={cycle.id} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl bg-slate-50 px-4 py-3"><div><p className="text-sm font-semibold text-slate-800">Cycle {index + 1}</p><p className="mt-0.5 text-xs text-slate-500">Started {formatDate(cycle.startDate)}{cycle.endDate ? ` · Ended ${formatDate(cycle.endDate)}` : ' · Current / end not recorded'}</p></div><span className="rounded-full bg-white px-3 py-1 text-xs font-semibold text-slate-600">{cycle.lengthDays === null ? 'Length not recorded' : `${cycle.lengthDays} days`}</span></div>)}</div></div>
    <div className="rounded-3xl bg-gradient-to-br from-[#eaf4ff] to-[#f3eeff] p-6"><p className="text-sm font-bold text-indigo-700">Profile on record</p><dl className="mt-4 space-y-3 text-sm"><ProfileRow label="Age band" value={patient.profile.ageBand} /><ProfileRow label="Cycle regularity" value={humanise(patient.profile.cycleRegularity)} /><ProfileRow label="Cycle estimate" value={patient.profile.cycleLengthEstimate === null ? null : `${patient.profile.cycleLengthEstimate} days`} /><ProfileRow label="Time zone" value={patient.profile.timezone} /></dl><p className="mt-5 text-xs leading-5 text-slate-500">Unknown fields remain “Not recorded”; this view does not infer or add health information.</p></div></section>
  <section className="mt-7 rounded-3xl border border-blue-100 bg-white p-6"><div className="flex items-center justify-between gap-4"><div><h2 className="text-lg font-bold text-slate-900">Recent migraine history</h2><p className="mt-1 text-sm text-slate-500">Most recent recorded episodes in this synthetic dataset.</p></div><button onClick={() => navigate('diary')} className="text-sm font-semibold text-indigo-600">View diary</button></div><div className="mt-5 grid gap-3 md:grid-cols-3">{[...patient.episodes].sort((a, b) => b.startAt.localeCompare(a.startAt)).slice(0, 3).map((episode) => <article key={episode.id} className="rounded-2xl bg-slate-50 p-4"><p className="text-xs font-semibold text-indigo-600">{formatDate(episode.startAt.slice(0, 10))}</p><p className="mt-2 text-sm font-bold text-slate-800">{episode.endAt === null ? 'Still going' : 'Episode closed'}</p><p className="mt-1 text-xs text-slate-500">Severity: {episode.peakSeverity === null ? 'Not recorded' : `${episode.peakSeverity}/10`} · Duration: {formatDuration(episode.durationMin)}</p></article>)}</div></section>
  </> }
function StatusCard({ label, value, detail, accent }) { const styles = { blue: 'border-blue-100 bg-blue-50', violet: 'border-violet-100 bg-violet-50', sky: 'border-sky-100 bg-sky-50' }; return <article className={`rounded-3xl border p-5 ${styles[accent]}`}><p className="text-sm font-semibold text-slate-600">{label}</p><p className="mt-3 text-3xl font-bold tracking-tight text-slate-900">{value}</p><p className="mt-2 text-xs text-slate-500">{detail}</p></article> }
function ProfileRow({ label, value }) { return <div className="flex items-center justify-between gap-3 border-b border-white/80 pb-2 last:border-0"><dt className="text-slate-500">{label}</dt><dd className="text-right font-semibold text-slate-800">{value ?? 'Not recorded'}</dd></div> }
function formatDate(value) { return new Intl.DateTimeFormat('en', { month: 'short', day: 'numeric', year: 'numeric', timeZone: 'UTC' }).format(new Date(`${value}T12:00:00Z`)) }
function formatDuration(value) { return value === null ? 'Not recorded' : `${Math.floor(value / 60)}h ${value % 60}m` }
function humanise(value) { return value ? value.replaceAll('_', ' ') : null }
function Placeholder({ page }) { return <section className="grid min-h-[65vh] place-items-center rounded-3xl border border-dashed border-indigo-200 bg-white p-8 text-center"><div><div className="mx-auto grid size-14 place-items-center rounded-2xl bg-indigo-50 text-2xl text-indigo-600">⌁</div><h1 className="mt-5 text-3xl font-bold tracking-tight text-slate-900">{page[0]}</h1><p className="mx-auto mt-3 max-w-md text-slate-600">{page[1]}</p><p className="mt-6 text-sm font-medium text-violet-700">Coming soon — placeholder page</p><p className="mt-2 text-xs text-slate-400">All future example data will be synthetic.</p></div></section> }
